name: "Publish"

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: "Publish content"
        run: bash scripts/publish.sh "bash scripts/generate.sh" "${{ secrets.USER_GITHUB_TOKEN }}" "${GITHUB_REPOSITORY}"